services:
#    formular class
    app.formular.generic:
        abstract: true
        class: AppBundle\Service\DocumentForm\FormularGeneric
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @file_locator]

    app.formular.generic_unique:
        abstract: true
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularGenericUnique

    app.formular.evidenta_gestiunii_deseurilor:
        parent: app.formular.generic_unique
        class: AppBundle\Service\DocumentForm\FormularEvidentaGestiuniiDeseurilorService

    app.formular.convocator_c_s_s_m:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularConvocatorCSSMService

    app.formular.decizie_componenta_c_s_s_m:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularDecizieComponentaCSSM

    app.formular.decizie_personal_cu_atributii:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularDeciziePersonalCuAtributii

    app.formular.decizie_comisie_cercetare_accidente:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularDecizieComisieCercetareAccidente

    app.formular.decizie_organizare_activitate_s_s_m:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularDecizieOrganizareActivitateSSM

    app.formular.proces_verbal_sedinta_c_s_s_m:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularProcesVerbalSedintaCSSM

    app.formular.proces_verbal_control:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularProcesVerbalControl

    app.formular.permis_de_lucru_cu_foc:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularPermisDeLucruCuFoc

    app.formular.decizie_personal_cu_atributii_p_s_i:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularDeciziePersonalCuAtributiiPSI

    app.formular.decizie_personal_cu_atributii2:
        parent: app.formular.generic
        class: AppBundle\Service\DocumentForm\FormularDeciziePersonalCuAtributii2