services:
    app.form.flow.evidenta_gestiunii_deseurilor:
        class: AppBundle\Form\Flow\DocumentForm\EvidentaGestiuniiDeseurilorFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.convocator_c_s_s_m:
        class: AppBundle\Form\Flow\DocumentForm\ConvocatorCSSMFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.decizie_componenta_c_s_s_m:
        class: AppBundle\Form\Flow\DocumentForm\DecizieComponentaCSSMFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.decizie_personal_cu_atributii:
        class: AppBundle\Form\Flow\DocumentForm\DeciziePersonalCuAtributiiFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.decizie_comisie_cercetare_accidente:
        class: AppBundle\Form\Flow\DocumentForm\DecizieComisieCercetareAccidenteFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.decizie_organizare_activitate_s_s_m:
        class: AppBundle\Form\Flow\DocumentForm\DecizieOrganizareActivitateSSMFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.proces_verbal_sedinta_c_s_s_m:
        class: AppBundle\Form\Flow\DocumentForm\ProcesVerbalSedintaCSSMFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.proces_verbal_control:
        class: AppBundle\Form\Flow\DocumentForm\ProcesVerbalControlFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.permis_de_lucru_cu_foc:
        class: AppBundle\Form\Flow\DocumentForm\PermisDeLucruCuFocFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.decizie_personal_cu_atributii_p_s_i:
        class: AppBundle\Form\Flow\DocumentForm\DeciziePersonalCuAtributiiPSIFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.decizie_personal_cu_atributii2:
        class: AppBundle\Form\Flow\DocumentForm\DeciziePersonalCuAtributii2Flow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]

    app.form.flow.register:
        class: AppBundle\Form\Flow\RegisterFlow
        parent: craue.form.flow
        scope: request
