services:
    #    website
    app.mailer:
        class: AppBundle\Service\MailerService
        arguments: ['@mailer', '@templating', '@translator', %email_from%, %contact_email%, %email_title%, %report_email%]
    app.credits_usage:
        class: AppBundle\Service\CreditsUsageService
        arguments: [@doctrine.orm.entity_manager, @translator, @app.user, @event_dispatcher]
    app.media:
        class: AppBundle\Service\MediaService
        arguments: [@doctrine.orm.entity_manager]
    app.user:
        class: AppBundle\Service\UserService
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory, @security.authorization_checker, @security.token_storage, @session, @translator]
    app.order:
        class: AppBundle\Service\OrderService
        arguments: [@doctrine.orm.entity_manager, @translator, @security.token_storage, @session, @app.mailer, @knp_snappy.pdf, '@templating', %invoice_dir%, %invoice_name%]
    app.security.authentication_handler:
        class: AppBundle\Listener\AuthenticationHandler
        public: false
        arguments: [@router, @session, @app.user, @app.credits_usage, @event_dispatcher]
    app.media.security.user_strategy:
        class: AppBundle\Security\Sonata\UserDownloadStrategy
        arguments: [@translator, @security.authorization_checker, @security.token_storage, @app.user, @app.credits_usage, @app.media]
    app.container_aware_type:
        class: AppBundle\Form\Type\ContainerAwareType
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: form.type, alias: 'container_aware' }

    #   twig
    app.twig.extension.json_decode:
        class: AppBundle\Twig\Extension\VarsExtension
        tags:
            - { name: twig.extension }
        arguments: ['@service_container']

    #   event listener
    app.event.credits_used:
        class: AppBundle\EventListener\CreditUsageListener
        tags:
            - {name: kernel.event_listener, event: app.event.credits_used, method: handlerCreditUsed}
        arguments: ['@app.user', '@doctrine.orm.entity_manager', '@translator']

    app.event.update_credits:
        class: AppBundle\EventListener\CreditUsageListener
        tags:
            - {name: kernel.event_listener, event: app.event.update_credits, method: handlerUpdateCredits}
        arguments: ['@app.user', '@doctrine.orm.entity_manager', '@translator']
