<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditsUsageRepository extends EntityRepository
{

    public function findAllValidUserDocuments($userId, $domainId = null)
    {
        $queryBuilder = $this->getEntityManager()
          ->createQueryBuilder()
          ->select('DISTINCT(d.id) as id, d.title, cu.createdAt as unlockDate, cu.credit, cu.expireDate as date, sd.name as subDomain, dom.name as domain')
          ->from('Application\Sonata\MediaBundle\Entity\Media', 'd')
          ->join('AppBundle:CreditsUsage', 'cu', 'WITH', 'cu.document = d')
          ->join('AppBundle:SubDomain', 'sd', 'WITH', 'd.subdomain = sd')
          ->join('AppBundle:Domain', 'dom', 'WITH', 'sd.domain = dom')
          ->where('cu.user = :user')
          ->setParameter('user', $userId)
          ->andWhere('cu.expireDate > :now')
          ->setParameter('now', new \DateTime);
        if (null !== $domainId) {
            $queryBuilder->andWhere('sd.domain = :domain')
              ->setParameter('domain', $domainId);
        }
        $queryBuilder->orderBy('dom.id')
          ->orderBy('sd.id');

        $query = $queryBuilder->getQuery();

        return $query->getArrayResult();
    }

    public function findAllUserDocuments($userId)
    {
        $queryBuilder = $this->getEntityManager()
          ->createQueryBuilder()
          ->select('d.id, d.title, cu.mentions, cu.createdAt as unlockDate, cu.credit, cu.expireDate')
          ->from('Application\Sonata\MediaBundle\Entity\Media', 'd')
          ->join('AppBundle:CreditsUsage', 'cu', 'WITH', 'cu.document = d')
          ->where('cu.user = :user')
          ->setParameter('user', $userId)
          ->orderBy('unlockDate', 'DESC');

        $query = $queryBuilder->getQuery();

        return $query->getArrayResult();
    }

    public function findValidUserDocument($userId, $documentId)
    {
        $queryBuilder = $this->getEntityManager()
          ->createQueryBuilder()
          ->select('d.id')
          ->from('Application\Sonata\MediaBundle\Entity\Media', 'd')
          ->join('AppBundle:CreditsUsage', 'cu', 'WITH', 'cu.document = d')
          ->where('cu.user = :user')
          ->setParameter('user', $userId)
          ->andWhere('cu.expireDate > :now')
          ->setParameter('now', new \DateTime)
          ->andWhere('d.id = :document')
          ->setParameter('document', $documentId);

        $query = $queryBuilder->getQuery();

        return $query->getArrayResult();
    }

    public function findTotalUsedCredits($userId)
    {
        $queryBuilder = $this->getEntityManager()
          ->createQueryBuilder()
          ->select('sum(cu.credit)')
          ->from('AppBundle:CreditsUsage', 'cu')
          ->where('cu.user = :user')
          ->setParameter('user', $userId);

        $query = $queryBuilder->getQuery();
        $result = $query->getSingleScalarResult();

        return ($result) ? $result : 0;
    }

}