<?php
/**
 * Created by PhpStorm.
 * User: adriancalugar
 * Date: 12/02/2017
 * Time: 12:43
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{

    public function getChoicesForAdmin()
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('d')
            ->from('AppBundle:Domain', 'd')
        ;

        $query = $qb->getQuery();
        $result = $query->getResult();

        $returnArray = [];

        foreach ($result as $domain) {
            $returnArray[$domain->getName()] = $domain->getSubdomains();
        }

        return $returnArray;
    }
}