<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{

    public function findAllValidUserOrders($user, $now)
    {
        $queryBuilder = $this->getEntityManager()
          ->createQueryBuilder()
          ->select('DISTINCT(d.id) as id')
          ->from('AppBundle:Order', 'o')
          ->join('o.domains', 'd')
          ->where('o.active = TRUE')
          ->andWhere('o.user = :user')
          ->setParameter('user', $user)
          ->andWhere('o.endingDate > :now')
          ->setParameter('now', $now);

        $query = $queryBuilder->getQuery();

        return $query->getArrayResult();
    }

}