<?php
/**
 * Created by PhpStorm.
 * User: adriancalugar
 * Date: 11/02/2017
 * Time: 16:53
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubDomainRepository extends EntityRepository
{


}