imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: documentForm/evidenta_gestiunii_deseurilor.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ro
    sonata.user.admin.groupname: User
    sonata.user.admin.user.class: AppBundle\Admin\UserAdmin
    sonata.user.admin.user.controller: AppBundle:Admin\User
    sonata.user.admin.user.translation_domain: SonataAdminUserBundle
    sonata.media.provider.file.class: AppBundle\Provider\CustomFileProvider
    sonata.media.admin.media.class: AppBundle\Admin\MediaAdmin
    stof_doctrine_extensions.listener.softdeleteable.class: AppBundle\Listener\SoftDeleteableListener

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        egd:
            tip_stocare: %tip_stocare%
            mod_tratare: %mod_tratare%
            scop_tratare: %scop_tratare%
            mijloc_transport: %mijloc_transport%
            destinatia: %destinatia%
            operatia_valorificare_deseu: %operatia_valorificare_deseu%
            operatia_eliminare_deseu: %operatia_eliminare_deseu%
            unique:
                operatia: %operatia%
            autocomplete:
                stare_fizica: %stare_fizica%
                unitate_masura: %unitate_masura%
            
    #sonata
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'sonata/media_widgets.html.twig'

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }



# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    title: Online51
    options:
        html5_validate: true
    templates:
        layout: sonata/layout.html.twig
        batch: sonata/batch.html.twig

sonata_user:
    security_acl: false
    manager_type: orm

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.formatter.block.formatter: # used to display sonata formatters

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: []
            # Twig formatter cannot have extensions

sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.file
                - sonata.media.provider.image
                - sonata.media.provider.video
            formats:
                small: { width: 75 , quality: 70}
                big:   { width: 500 , quality: 70}
            download:
                strategy: app.media.security.user_strategy
                mode: http
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    providers:
        file:
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', application/vnd.openxmlformats-officedocument.wordprocessingml.document]

vich_uploader:
    db_driver: orm
    mappings:
        upload_image:
            uri_prefix:         /images/uploadFile
            upload_destination: %kernel.root_dir%/../web/images/uploadFile
            inject_on_load:     false
            namer:              uploadFile.namer
            delete_on_update:   true
            delete_on_remove:   true

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~

stof_doctrine_extensions:
    orm:
        default:
            softdeleteable: true

knp_doctrine_behaviors:
    sluggable:      true

gregwar_captcha: ~

knp_snappy:
    pdf:
        enabled:    true
        binary:      %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:    []

boekkooi_jquery_validation:
    form:
        enabled: true
    twig:
        enabled: true

knp_paginator:
    template:
        pagination: pagination/twitter_bootstrap_v3_pagination.html.twig    # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template