# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.subscription:
        class: AppBundle\Admin\SubscriptionAdmin
        arguments: [~, AppBundle\Entity\Subscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Subscription, group: Data }
    admin.domain:
        class: AppBundle\Admin\DomainAdmin
        arguments: [~, AppBundle\Entity\Domain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Domain, group: Data }
    admin.subdomain:
        class: AppBundle\Admin\SubDomainAdmin
        arguments: [~, AppBundle\Entity\SubDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: SubDomain, group: Data }
