# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.subscription:
        class: AppBundle\Admin\SubscriptionAdmin
        arguments: [~, AppBundle\Entity\Subscription, AppBundle:Admin\Subscription]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.subscription, group: admin_group_data }
    admin.domain:
        class: AppBundle\Admin\DomainAdmin
        arguments: [~, AppBundle\Entity\Domain, AppBundle:Admin\Domain]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.domain, group: admin_group_data }
    admin.subdomain:
        class: AppBundle\Admin\SubDomainAdmin
        arguments: [~, AppBundle\Entity\SubDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.sub_domain, group: admin_group_data }
    admin.order:
        class: AppBundle\Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, AppBundle:Admin\Order]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.order, group: admin_group_credit }
        calls:
            - [setTemplates, [{ base_list_field: sonata/order_base_list_field.html.twig }]]
    admin.creditsusage:
        class: AppBundle\Admin\CreditsUsageAdmin
        arguments: [~, AppBundle\Entity\CreditsUsage, AppBundle:Admin\CreditsUsage]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.credits_usage, group: admin_group_credit }
        calls:
            - [setTemplates, [{ base_list_field: sonata/credits_usage_base_list_field.html.twig }]]
    admin.ad:
        class: AppBundle\Admin\AdAdmin
        arguments: [~, AppBundle\Entity\Ad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.ad, group: admin_group_website }
        calls:
            - [setTemplates, [{ base_list_field: sonata/ad_base_list_field.html.twig }]]
    admin.area:
        class: AppBundle\Admin\ROAreaAdmin
        arguments: [~, AppBundle\Entity\ROArea, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.area, group: admin_group_website }
    admin.document:
        class: AppBundle\Admin\DocumentAdmin
        arguments: [~, AppBundle\Entity\Document, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.document, group: sonata_media }
        calls:
            - [setTemplates, [{ base_list_field: sonata/document_base_list_field.html.twig }]]
    admin.video:
        class: AppBundle\Admin\VideoAdmin
        arguments: [~, AppBundle\Entity\Video, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.video, group: sonata_media }
        calls:
            - [setTemplates, [{ base_list_field: sonata/video_base_list_field.html.twig }]]
    admin.formular:
        class: AppBundle\Admin\FormularAdmin
        arguments: [~, AppBundle\Entity\Formular, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.formular, group: sonata_media }

    app.mailer:
        class:     AppBundle\Service\MailerService
        arguments: ['@mailer', '@templating', '@translator', %email_from%, %contact_email%, %email_title%, %report_email%]
    app.user_helper:
        class:     AppBundle\Service\UserHelperService
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory, @security.authorization_checker, @security.token_storage, @session, @translator]
    app.order_helper:
        class:     AppBundle\Service\OrderHelperService
        arguments: [@doctrine.orm.entity_manager, @translator, @security.token_storage, @session, @app.mailer, @knp_snappy.pdf, '@templating', %invoice_dir%, %invoice_name%]
    app.formular_helper:
        class:     AppBundle\Service\FormularHelperService
        arguments: ['@translator', %tip_deseu%, %operatia%]
    app.security.authentication_handler:
        class: AppBundle\Listener\AuthenticationHandler
        public: false
        arguments: [@router, @session, @app.user_helper]
    app.media.security.user_strategy:
        class:     AppBundle\Security\Sonata\UserDownloadStrategy
        arguments: [@translator, @security.authorization_checker, @security.token_storage, @app.user_helper]
    app.container_aware_type:
        class: AppBundle\Form\Type\ContainerAwareType
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: form.type, alias: 'container_aware' }
    app.sonata_security_roles:
        class: AppBundle\Form\Type\AppSecurityRolesType
        tags:
            - { name: form.type, alias: 'app_sonata_security_roles' }
        arguments: [@sonata.user.editable_role_builder]
    
    app.form.flow.egd:
        class: AppBundle\Form\Flow\DocumentForm\EvidentaGestiuniiDeseurilorFlow
        parent: craue.form.flow
        scope: request
        arguments: [@doctrine.orm.entity_manager]


    sonata.media.provider.video:
        class: AppBundle\Provider\VideoFileProvider
        arguments: 
            - sonata.media.provider.video
            - @sonata.media.filesystem.local
            - @sonata.media.cdn.server
            - @sonata.media.generator.default
            - @sonata.media.thumbnail.format
            - ['mp4']
            - ['video/mp4']
        tags:
            - { name: sonata.media.provider }
            
    app.twig.extension.json_decode:
        class: AppBundle\Twig\Extension\VarsExtension
        tags:
            - { name: twig.extension }
        arguments: ['@service_container']