# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    admin
    admin.subscription:
        class: AppBundle\Admin\SubscriptionAdmin
        arguments: [~, AppBundle\Entity\Subscription, AppBundle:Admin\Subscription]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.subscription, group: admin_group_data }
    admin.domain:
        class: AppBundle\Admin\DomainAdmin
        arguments: [~, AppBundle\Entity\Domain, AppBundle:Admin\Domain]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.domain, group: admin_group_data }
    admin.subdomain:
        class: AppBundle\Admin\SubDomainAdmin
        arguments: [~, AppBundle\Entity\SubDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.sub_domain, group: admin_group_data }
    admin.folder:
        class: AppBundle\Admin\FolderAdmin
        arguments: [~, AppBundle\Entity\Folder, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.folder, group: admin_group_data }
    admin.order:
        class: AppBundle\Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, AppBundle:Admin\Order]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.order, group: admin_group_credit }
        calls:
            - [setTemplates, [{ base_list_field: sonata/order_base_list_field.html.twig }]]
    admin.creditsusage:
        class: AppBundle\Admin\CreditsUsageAdmin
        arguments: [~, AppBundle\Entity\CreditsUsage, AppBundle:Admin\CreditsUsage]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.credits_usage, group: admin_group_credit }
        calls:
            - [setTemplates, [{ base_list_field: sonata/credits_usage_base_list_field.html.twig }]]
    admin.ad:
        class: AppBundle\Admin\AdAdmin
        arguments: [~, AppBundle\Entity\Ad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.ad, group: admin_group_website }
        calls:
            - [setTemplates, [{ base_list_field: sonata/ad_base_list_field.html.twig }]]
    admin.area:
        class: AppBundle\Admin\ROAreaAdmin
        arguments: [~, AppBundle\Entity\ROArea, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.area, group: admin_group_website }
    admin.document:
        class: AppBundle\Admin\DocumentAdmin
        arguments: [~, AppBundle\Entity\Document, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.document, group: sonata_media }
        calls:
            - [setTemplates, [{ base_list_field: sonata/document_base_list_field.html.twig }]]
    admin.video:
        class: AppBundle\Admin\VideoAdmin
        arguments: [~, AppBundle\Entity\Video, AppBundle:Admin\Video]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.video, group: sonata_media }
        calls:
            - [setTemplates, [{ base_list_field: sonata/video_base_list_field.html.twig }]]
    admin.formular:
        class: AppBundle\Admin\FormularAdmin
        arguments: [~, AppBundle\Entity\Formular, AppBundle:Admin\Formular]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.formular, group: sonata_media }
    admin.profile:
        class: AppBundle\Admin\ProfileAdmin
        arguments: [~, AppBundle\Entity\Profile, AppBundle:Admin\Profile]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.profile, group: %sonata.user.admin.groupname%, show_in_dashboard: false }
    app.sonata_security_roles:
        class: AppBundle\Form\Type\AppSecurityRolesType
        tags:
            - { name: form.type, alias: 'app_sonata_security_roles' }
        arguments: [@sonata.user.editable_role_builder]
    sonata.media.provider.video:
        class: AppBundle\Provider\VideoFileProvider
        arguments: 
            - sonata.media.provider.video
            - @sonata.media.filesystem.local
            - @sonata.media.cdn.server
            - @sonata.media.generator.default
            - @sonata.media.thumbnail.format
            - ['mp4']
            - ['video/mp4']
        tags:
            - { name: sonata.media.provider }
