# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.subscription:
        class: AppBundle\Admin\SubscriptionAdmin
        arguments: [~, AppBundle\Entity\Subscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Subscription, group: Data }
    admin.domain:
        class: AppBundle\Admin\DomainAdmin
        arguments: [~, AppBundle\Entity\Domain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Domain, group: Data }
    admin.subdomain:
        class: AppBundle\Admin\SubDomainAdmin
        arguments: [~, AppBundle\Entity\SubDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: SubDomain, group: Data }
    admin.usersubscription:
        class: AppBundle\Admin\UserSubscriptionAdmin
        arguments: [~, AppBundle\Entity\UserSubscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: UserSubscription, group: Subscription }
    admin.usersubscriptiondomain:
        class: AppBundle\Admin\UserSubscriptionDomainAdmin
        arguments: [~, AppBundle\Entity\UserSubscriptionDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: UserSubscriptionDomain, group: Subscription }
    admin.credits:
        class: AppBundle\Admin\CreditsAdmin
        arguments: [~, AppBundle\Entity\Credits, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Credits, group: Credit }
    admin.creditsusage:
        class: AppBundle\Admin\CreditsUsageAdmin
        arguments: [~, AppBundle\Entity\CreditsUsage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CreditsUsage, group: Credit }
    admin.ad:
        class: AppBundle\Admin\AdAdmin
        arguments: [~, AppBundle\Entity\Ad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ad, group: Website }
            
    sonata_admin_image_file:
        class: AppBundle\Form\Type\AdminImageFileType
        tags:
            - { name: form.type }
    uploadFile.namer:
        class: AppBundle\Util\FileNamer
