# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.subscription:
        class: AppBundle\Admin\SubscriptionAdmin
        arguments: [~, AppBundle\Entity\Subscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.subscription, group: admin_group_data }
    admin.domain:
        class: AppBundle\Admin\DomainAdmin
        arguments: [~, AppBundle\Entity\Domain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.domain, group: admin_group_data }
    admin.subdomain:
        class: AppBundle\Admin\SubDomainAdmin
        arguments: [~, AppBundle\Entity\SubDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.sub_domain, group: admin_group_data }
    admin.usersubscription:
        class: AppBundle\Admin\UserSubscriptionAdmin
        arguments: [~, AppBundle\Entity\UserSubscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.user_subscription, group: admin_group_subscription }
    admin.usersubscriptiondomain:
        class: AppBundle\Admin\UserSubscriptionDomainAdmin
        arguments: [~, AppBundle\Entity\UserSubscriptionDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.user_subscription_domain, group: admin_group_subscription }
    admin.credits:
        class: AppBundle\Admin\CreditsAdmin
        arguments: [~, AppBundle\Entity\Credits, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.credits, group: admin_group_credit }
    admin.creditsusage:
        class: AppBundle\Admin\CreditsUsageAdmin
        arguments: [~, AppBundle\Entity\CreditsUsage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.credits_usage, group: admin_group_credit }
    admin.ad:
        class: AppBundle\Admin\AdAdmin
        arguments: [~, AppBundle\Entity\Ad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin_label.ad, group: admin_group_website }
            
    sonata_admin_image_file:
        class: AppBundle\Form\Type\AdminImageFileType
        tags:
            - { name: form.type }
    uploadFile.namer:
        class: AppBundle\Util\FileNamer
    app.mailer:
        class:     AppBundle\Service\MailerService
        arguments: ['@mailer', '@templating', '@translator', %email_from%, %contact_email%]
