Application\Sonata\UserBundle\Entity\User:
    properties:
        uploadImage:
            - File:
                mimeTypes: ["image/jpeg", "image/png"]
                mimeTypesMessage: Please upload a valid image.
                groups: [CustomRegistration, Registration, Profile]
        noEmployees:
            - GreaterThanOrEqual:
                value: 0
                groups: [Registration, Profile]

